name: 自动push防止Actions自动停止

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号0点执行一次
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # 此权限用于调用API，比推送权限更安全
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
