name: Keepalive Workflow
on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号0点执行一次，足够防止禁用
  workflow_dispatch:      # 允许手动触发

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # 仅授予调用API的最小权限
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Keepalive workflow
        uses: gautamkrishnar/keepalive-workflow@v2
